name: Evaluate Student Submission

on:
  repository_dispatch:
    types: [evaluate_submission]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student submission
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.student_repo_link }}
          path: student-code

      - name: Checkout private tests repo
        uses: actions/checkout@v4
        with:
          repository: yahia997/private
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: tests-folder

      - name: Run evaluation script
        run: |
          python3 tests-folder/hello.py ./student-code/ ${{ github.event.client_payload.submission_id }}